version: '3'
services:
  cloud-firestore:
    build:
      context: .
      dockerfile: firestore/Dockerfile
    image: cloud-firestore
    ports:
      - 4000:4000
      - 5000:5000
      - 5001:5001
      - 8080:8080
      - 8085:8085
      - 9000:9000
    environment:
      CLOUDSDK_CORE_PROJECT: local

  microkonf:
    image: microkonf:test
    depends_on:
      - cloud-firestore
    ports:
      - 8081:8081
    environment:
      FIRESTORE_EMULATOR_HOST: cloud-firestore:8080
      GOOGLE_CLOUD_PROJECT: local
      MICRONAUT_ENVIRONMENTS: dev