resources:
  - name: Partnership Proposition
    url: https://docs.google.com/presentation/d/e/2PACX-1vQG2XbNmj7WClus0yda00zmLOBk53yG0fSW_je97TulDSxpwu_FLbkEQwFTj_m_Rg8T2MdiWjlXbmCy/pub?start=false&loop=false&delayms=60000