partners:
  - name: General Partners
    items:
      - name: Google
        url: https://www.google.com.ua/intl/en/about/
        logo: /static/images/logos/google.svg
      - name: JetBrains
        url: https://www.jetbrains.com/company/
        logo: /static/images/logos/jetbrains.svg
  - name: Venue Partners
    items:
      - name: Technopark Ankudinovka
        url: https://www.itpark-nn.com/
        logo: /static/images/logos/ankudinovka.png
  - name: Gold Partner
    items:
      - name: EPAM Systems
        url: https://www.epam.com/
        logo: /static/images/logos/epam-systems.png
  - name: Silver Partner
    items:
      - name: Five9
        url: https://www.five9.com/
        logo: /static/images/logos/five9.png
  - name: Travel Partner
    items:
      - name: Humans Net, Inc
        url: https://humans.net/
        logo: /static/images/logos/humans.jpg
