micronaut:
  server:
    port: 8080
  application:
    name: microkonf
  router:
    static-resources:
      default:
        enabled: true
        mapping: /public/**
        paths:
          - classpath:public
      serviceWorker:
        enabled: true
        mapping: /**
        paths:
          - classpath:public/js/sw

datasources:
  gcp:
    firestore:
      sa: firebase-adminsdk.json

render:
  cache:
    folder: public
    excludeHaving:
      - sw