micronaut:
  application:
    name: microkonf
  router:
    static-resources:
      default:
        enabled: true
        mapping: /public/**
        paths:
          - classpath:public

render:
  # Defines order of elements rendering on the page
  # Must cooperate with files from /views/blocks
  blocks:
    path: ${BLOCKS_CONFIGURATION:}
    index:
      - about
      - social
      - tickets
      - organizers
      - gallery
      - venue
      - partners