micronaut:
  server:
    port: 8081
  application:
    name: microkonf
  router:
    static-resources:
      default:
        enabled: true
        mapping: /public/**
        paths:
          - classpath:public
      serviceWorker:
        enabled: true
        mapping: /**
        paths:
          - classpath:public/js/sw

datasources:
  gcp:
    firestore:
      emulator:
        enabled: true

render:
  # Defines order of elements rendering on the page
  # Must cooperate with files from /views/blocks
  blocks:
    path: ${BLOCKS_CONFIGURATION:}
    index:
      - welcome
      - about
      - social
      - tickets
      - organizers
      - gallery
      - venue
      - partners
  cache:
    folder: public
    excludeHaving:
      - sw