css:
  - href: https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css
  - href: https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
js:
  - href: https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js
  - href: https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js
  - href: https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js